UpdateNotification: true
Crops: true
AutoFeed: true
NoTrample: true
MineSpawners: true
BannedSpawners:
  - Pig
  - Cow
  - Villager
Tools:
  Workbench: true
  BetterHoes: false
  InfiniteTorch: true
  TotemInInv: true
  SwitchArmor: true
  AutoArmor:
    Enabled: true
    Priorities:
      Diamond: 5
      Iron: 4
      Chain: 3
      Gold: 2
      Leather: 1
VillagerAdditions:
  Leash: true
  Drops: true
  EmeraldDropChance:
    Drop: 2
    DropChance: 50
    Randomize: true
CustomRecipes:
  Chest: true
Language: english
