name: SmallAdditions
main: si.zbe.smalladd.Main
author: TheZbe
description: 'Features you wish were already included in Minecraft.'
api-version: 1.13
version: ${project.version}
commands:
   autoarmor:
      description: Enables or disables AutoArmor.
      usage: /<command>
      aliases: aa
   autofeed:
      description: Enables or disables AutoFeed.
      usage: /<command> <atribute>
      aliases: af
   portableworkbench:
      description: Sets name to 'Portable Workbench'.
      usage: /<command>
      aliases: pwb
   infinitetorch:
      description: Sets name to 'Portable Workbench'.
      usage: /<command>
      aliases: it
   saupdate:
      description: Checks for updates.
      usage: /<command>
      aliases: sau
   sadeath:
      description: Teleports to last known death location.
      usage: /<command>
      aliases: sad
permissions:
  smalladd.*:
    description: 'Gives access to all SmallAdditions features.'
    default: op
    children:
      smalladd.crop.*: true
      smalladd.autofeed: true
      smalladd.notrample: true
      smalladd.admin: true
      smalladd.villagerleash: true
      smalladd.tool.*: true
      smalladd.spawner: true
  smalladd.admin:
    description: 'Allows you to check for updates.'
    default: false
  smalladd.tool.*:
     description: 'Usage of all tools this plugin offers'
     children:
        smalladd.tool.workbench: true
        smalladd.tool.torch: true
        smalladd.tool.hoe: true
        smalladd.tool.armor: true
  smalladd.villagerleash:
    description: 'Allows you to leash a villager.'
    default: false
  smalladd.spawner:
    description: 'Allows you to mine spawners.'
    default: false
  smalladd.tool.workbench:
    description: 'Allows you to open portable workbench.'
    default: false
  smalladd.tool.torch:
    description: 'Allows you to have an infinite torch.'
    default: false
  smalladd.tool.hoe:
    description: 'Allows you to use improved hoes.'
    default: false
  smalladd.tool.armor:
    description: 'Allows you to switch armor.'
    default: false
  smalladd.autofeed:
    description: 'Allows you to get fed from items in your inventory.'
    default: false
  smalladd.notrample:
    description: 'Prevents player from trampling crops.'
    default: false
  smalladd.crop.*:
    description: 'Allows you to easily pick up and replant crops.'
    default: false
    children:
      smalladd.crop.wheat: true
      smalladd.crop.potato: true
      smalladd.crop.carrot: true
      smalladd.crop.beetroot: true
      smalladd.crop.netherwart: true
  smalladd.crop.wheat:
    description: 'Allows you to easily pick up and replant wheat.'
    default: false
  smalladd.crop.potato:
    description: 'Allows you to easily pick up and replant potatoes.'
    default: false
  smalladd.crop.carrot:
    description: 'Allows you to easily pick up and replant carrots.'
    default: false
  smalladd.crop.beetroot:
    description: 'Allows you to easily pick up and replant beetroots.'
    default: false
  smalladd.crop.netherwart:
    description: 'Allows you to easily pick up and replant nether warts.'
    default: false
